### ISSUE TITLE
Usage with nestjs (error The dependency 'mercurius' of plugin)

### ISSUE THREAD

**Issue by julestruong** [Eomm/mercurius-logging#7]
Hi there, first of all, thank you for this rep, this a good work and can't wait to use this plugin.

I'm currently using mercurius with nestjs and fastify.

My main.ts is something like this

```
async function bootstrap() {
  const fastifyInstance = fastify({
    logger: true,
    disableRequestLogging: true,
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(fastifyInstance),
    {
      bufferLogs: true,
      bodyParser: false, //@see app.module.ts
    },
  );

  await app.register(import('fastify-raw-body'), {
    field: 'rawBody', // change the default request.rawBody property name
    global: false, // add the rawBody to every request. **Default true**
    encoding: 'utf8', // set it to false to set rawBody as a Buffer **Default utf8**
    runFirst: true, // get the body before any preParsing hook change/uncompress it. **Default false**
    routes: ['/stripe/webhooks'], // array of routes, **`global`** will be ignored, wildcard routes not supported
  });

  await app.register(mercuriusLogging);
```

I have this error 

```
backend   | AssertionError [ERR_ASSERTION]: The dependency 'mercurius' of plugin 'mercurius-logging' is not registered
backend   |     at /usr/src/app/node_modules/fastify/lib/pluginUtils.js:64:5
backend   |     at Array.forEach (<anonymous>)
backend   |     at Object.checkDependencies (/usr/src/app/node_modules/fastify/lib/pluginUtils.js:63:16)
backend   |     at Object.registerPlugin (/usr/src/app/node_modules/fastify/lib/pluginUtils.js:135:21)
backend   |     at Boot.override (/usr/src/app/node_modules/fastify/lib/pluginOverride.js:28:57)
backend   |     at Plugin.exec (/usr/src/app/node_modules/avvio/plugin.js:79:33)
backend   |     at Boot.loadPlugin (/usr/src/app/node_modules/avvio/plugin.js:272:10)
backend   |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I understand the error, but i don't understand why i should register mercurius since it's done under the hood by https://www.npmjs.com/package/nestjs-mercurius and https://www.npmjs.com/package/@nestjs/platform-fastify

Can you help me with this ? or you've never used nestjs :(

**Comment by Eomm** [comment]
Hi, thanks for using it.

I think there are some issues with the modules' loading order.

Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
With it I can try to help you.

**Comment by julestruong** [comment]
Yes : https://github.com/julestruong/nestjs-graphql-mercurius-tmp

**Comment by julestruong** [comment]
For those who tried, i needed to create my custom driver : https://gist.github.com/julestruong/35268085d46c788a57ae778f61036d10
